export default {
  content: ["./index.html", "./src/**/*.{ts,tsx,html}"],
  theme: {
    extend: {
      colors: {
        primary: "#006875",
        primaryContainer: "#00e5ff",
        onPrimary: "#ffffff",
        onPrimaryContainer: "#003844",
        secondary: "#b60059",
        secondaryContainer: "#e30071",
        onSecondary: "#ffffff",
        secondaryFixed: "#ffd6e8",
        onSecondaryFixed: "#2a0e16",
        tertiary: "#5e4bff",
        tertiaryFixed: "#e3dcff",
        onTertiary: "#ffffff",
        onTertiaryFixed: "#1b1240",
        error: "#d22d55",
        onError: "#ffffff",
        surface: "#faf8ff",
        surfaceContainerLowest: "#ffffff",
        surfaceContainerLow: "#f2f3ff",
        surfaceContainer: "#ebedfc",
        surfaceContainerHighest: "#e0e4ff",
        onSurface: "#171b26",
        onSurfaceVariant: "#58626f",
        outline: "#6b7a7d",
        primaryFixed: "#c4f4ff",
        pureWhite: "#ffffff",
        deepObsidian: "#171b26",
        electricBlue: "#1b9dff",
        neonMagenta: "#ff4fc8",
      },
      fontFamily: {
        headline: ["Outfit", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
      },
      spacing: {
        "space-xxs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
        "space-4xl": "5rem",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontSize: {
        "display-hero": ["4rem", { lineHeight: "0.9", letterSpacing: "-0.06em" }],
        "display-hero-mobile": ["2.75rem", { lineHeight: "0.95", letterSpacing: "-0.05em" }],
        "headline-lg": ["2.5rem", { lineHeight: "1.1" }],
        "headline-lg-mobile": ["2rem", { lineHeight: "1.15" }],
        "headline-md": ["1.75rem", { lineHeight: "1.2" }],
        "headline-sm": ["1.125rem", { lineHeight: "1.35" }],
        "label-lg": ["1rem", { lineHeight: "1.2" }],
        "label-md": ["0.875rem", { lineHeight: "1.2" }],
        "label-tag": ["0.7rem", { lineHeight: "1.2" }],
        "body-lg": ["1.125rem", { lineHeight: "1.6" }],
        "body-md": ["1rem", { lineHeight: "1.6" }],
        "body-sm": ["0.875rem", { lineHeight: "1.5" }],
      },
      boxShadow: {
        soft: "0 8px 24px rgba(15, 23, 42, 0.08)",
      },
    },
  },
  plugins: [],
};
